# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python executable

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  build:
    if: ${{ github.event.pull_request.merged }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5
    - name: Build EXE from Python Script
      uses: Nuitka/Nuitka-Action@v0.4
      with:
        script-name: interface.py
        enable-plugins: pyqt5

